/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordecitas.pantallas;

import entidades.Cita;
import entidades.Especialidad;
import entidades.Medico;
import entidades.Paciente;
import gestordecitass.GestorDeCitas;

/**
 *
 * @author Estudiante
 */
public class JFrameCita extends javax.swing.JFrame {

    //El formulario padre 
    private JFrameGestorDeCitas padre;
    private Cita cita;
    private boolean Editando = false;
    private Medico medicoSeleccionado;
    private Paciente pacienteSeleccionado;
    private Especialidad especialidadSeleccionada;
    /**
     * Creates new form JFramCitas
     * @param padre
     */
    public JFrameCita(JFrameGestorDeCitas padre) {
        initComponents();
        this.padre=padre;
        
        cbespecialidad.removeAllItems();
        cbespecialidad.setEnabled(false);
        
        cbhora.removeAllItems();
        GestorDeCitas.Horariodispo.forEach((hora) -> {
            cbhora.addItem(hora);
        });
        cbfecha.removeAllItems();
        GestorDeCitas.DiasDisponibles.forEach((fecha) -> {
            cbfecha.addItem(fecha);
        });
        
        
        
    }
    public JFrameCita(JFrameGestorDeCitas padre,Cita cita) {
        initComponents();
        this.padre=padre;
        this.cita=cita;
        this.Editando=true;
        this.btnpaciente.setVisible(false);
        this.btnmedico.setVisible(false);
        this.btnguardar.setVisible(false);
        lblTitulo.setText("Visualizar Cita");
        this.txtmedico.setText(cita.getMedico().getDatosMostrar());
        this.txtpaciente.setText(cita.getPaciente().getDatosMostrar());
        cbespecialidad.removeAllItems();
        cbespecialidad.addItem(cita.getEspecialidad().getNombre());
        
        cbfecha.removeAllItems();
        cbfecha.addItem(GestorDeCitas.DiasDisponibles.get(cita.getFecha()));
        
        cbhora.removeAllItems();
        cbhora.addItem(GestorDeCitas.DiasDisponibles.get(cita.getHora()));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpaciente = new javax.swing.JTextField();
        txtmedico = new javax.swing.JTextField();
        btnpaciente = new javax.swing.JButton();
        btnmedico = new javax.swing.JButton();
        cbespecialidad = new javax.swing.JComboBox<>();
        cbfecha = new javax.swing.JComboBox<>();
        cbhora = new javax.swing.JComboBox<>();
        btnsalir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 255));

        btnpaciente.setBackground(new java.awt.Color(51, 255, 51));
        btnpaciente.setForeground(new java.awt.Color(102, 102, 102));
        btnpaciente.setText("Buscar Paciente");
        btnpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpacienteActionPerformed(evt);
            }
        });

        btnmedico.setBackground(new java.awt.Color(0, 255, 102));
        btnmedico.setForeground(new java.awt.Color(102, 102, 102));
        btnmedico.setText("Buscar Medico");
        btnmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicoActionPerformed(evt);
            }
        });

        cbespecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2", "item 3", "item 4" }));
        cbespecialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbespecialidadPropertyChange(evt);
            }
        });

        cbfecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2", "item 3", "item 4" }));

        cbhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2", "item 3", "item 4" }));

        btnsalir.setBackground(new java.awt.Color(255, 0, 0));
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(51, 51, 255));
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("NUEVA CITA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(cbhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbespecialidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 294, Short.MAX_VALUE)
                                .addComponent(txtmedico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpaciente, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnpaciente)
                            .addComponent(btnmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTitulo)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicoActionPerformed
        // TODO add your handling code here:
        
        JFrameMedicos pantallaMedicos=new JFrameMedicos(this);
        pantallaMedicos.setLocationRelativeTo(this);
        pantallaMedicos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmedicoActionPerformed

    private void btnpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpacienteActionPerformed
        // TODO add your handling code here:
        JFramePacientes pantallaPacientes=new JFramePacientes(this);
        pantallaPacientes.setLocationRelativeTo(this);
        pantallaPacientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnpacienteActionPerformed

    public void guardarCita(){
        
        
        if(medicoSeleccionado!=null &&pacienteSeleccionado!=null&&especialidadSeleccionada!=null){
            cita = new Cita(medicoSeleccionado,pacienteSeleccionado,especialidadSeleccionada);
            this.padre.agregarCita(cita);
        }
        
        
        
    }
    
    public void setPaciente(Paciente paciente){
        this.pacienteSeleccionado=paciente;
        txtpaciente.setText(paciente.getDatosMostrar());
    }
    public void setMedico(Medico medico){
        this.medicoSeleccionado=medico;
        
        cbespecialidad.removeAllItems();
        for(Especialidad espec : medico.getEspecialidades()){
            cbespecialidad.addItem(espec.getNombre());
        }
        cbespecialidad.setEnabled(true);
        
        
    }
    public void setEspecialidad(Especialidad especialidad ){
        this.especialidadSeleccionada=especialidad;
    }
    
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        guardarCita();
        salir();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cbespecialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbespecialidadPropertyChange
        // TODO add your handling code here:
        if(this.medicoSeleccionado!=null){
            Especialidad Espec =this.medicoSeleccionado.getEspecialidades().get(cbespecialidad.getSelectedIndex());
        setEspecialidad(Espec);
        }
        
    }//GEN-LAST:event_cbespecialidadPropertyChange

    /**
     * Debe abrir la ventana Paciente y 
     * permitirme escoger un paciente
     */
    private void buscarPaciente(){
        JFramePacientes paciente = new JFramePacientes(this);
        paciente.setLocationRelativeTo(null);
        paciente.setVisible(true);
    }
    
    private void salir(){
        //Muestra la ventana padre
        padre.setVisible(true);
        //Elmina esta ventana para no ocupar memoria
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameCita(new JFrameGestorDeCitas()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmedico;
    private javax.swing.JButton btnpaciente;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbespecialidad;
    private javax.swing.JComboBox<String> cbfecha;
    private javax.swing.JComboBox<String> cbhora;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtmedico;
    private javax.swing.JTextField txtpaciente;
    // End of variables declaration//GEN-END:variables
}
